// **********************************************************************
//
// Generated by the Orbix/E IDL to Java Translator
//
// Copyright (c) 2003
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 2.0.1

package jp.go.aist.jrl.vision.ModelInfoPackage;

//
// IDL:ModelInfo/NameSeq:1.0
//
final public class NameSeqHolder implements org.omg.CORBA.portable.Streamable
{
    public String[] value;

    public
    NameSeqHolder()
    {
    }

    public
    NameSeqHolder(String[] initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = NameSeqHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        NameSeqHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return NameSeqHelper.type();
    }
}
