// **********************************************************************
//
// Generated by the Orbix/E IDL to Java Translator
//
// Copyright (c) 2003
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 2.0.1

package jp.go.aist.jrl.vision.CameraPackage;

//
// IDL:Camera/CameraType:1.0
//
final public class CameraTypeHolder implements org.omg.CORBA.portable.Streamable
{
    public CameraType value;

    public
    CameraTypeHolder()
    {
    }

    public
    CameraTypeHolder(CameraType initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = CameraTypeHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        CameraTypeHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return CameraTypeHelper.type();
    }
}
