// **********************************************************************
//
// Generated by the Orbix/E IDL to Java Translator
//
// Copyright (c) 2003
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 2.0.1

package jp.go.aist.jrl.vision;

//
// IDL:ParserCharObject:1.0
//
public class _ParserCharObjectStub extends org.omg.CORBA.portable.ObjectImpl
                                   implements ParserCharObject
{
    private static final String[] _ob_ids_ =
    {
        "IDL:ParserCharObject:1.0",
    };

    public String[]
    _ids()
    {
        return _ob_ids_;
    }

    //
    // IDL:ParserCharObject/name:1.0
    //
    public String
    name()
    {
        org.omg.CORBA.portable.Delegate _ob_delegate = _get_delegate();
        while(true)
        {
            synchronized(_ob_delegate)
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("_get_name", true);
                    in = _invoke(out);
                    String _ob_r = in.read_string();
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
            }
        }
    }

    //
    // IDL:ParserCharObject/info:1.0
    //
    public String[]
    info()
    {
        org.omg.CORBA.portable.Delegate _ob_delegate = _get_delegate();
        while(true)
        {
            synchronized(_ob_delegate)
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("_get_info", true);
                    in = _invoke(out);
                    String[] _ob_r = stringSeqHelper.read(in);
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
            }
        }
    }

    //
    // IDL:ParserCharObject/modelObjectSeq:1.0
    //
    public ParserModelObject[]
    modelObjectSeq()
    {
        org.omg.CORBA.portable.Delegate _ob_delegate = _get_delegate();
        while(true)
        {
            synchronized(_ob_delegate)
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("_get_modelObjectSeq", true);
                    in = _invoke(out);
                    ParserModelObject[] _ob_r = ParserModelObjectSeqHelper.read(in);
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
            }
        }
    }
}
