// **********************************************************************
//
// Generated by the Orbix/E IDL to Java Translator
//
// Copyright (c) 2003
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 2.0.1

package jp.go.aist.jrl.vision;

//
// IDL:ParserModelObject:1.0
//
public class _ParserModelObjectStub extends org.omg.CORBA.portable.ObjectImpl
                                    implements ParserModelObject
{
    private static final String[] _ob_ids_ =
    {
        "IDL:ParserModelObject:1.0",
    };

    public String[]
    _ids()
    {
        return _ob_ids_;
    }

    //
    // IDL:ParserModelObject/positionGiven:1.0
    //
    public boolean
    positionGiven()
    {
        org.omg.CORBA.portable.Delegate _ob_delegate = _get_delegate();
        while(true)
        {
            synchronized(_ob_delegate)
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("_get_positionGiven", true);
                    in = _invoke(out);
                    boolean _ob_r = in.read_boolean();
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
            }
        }
    }

    //
    // IDL:ParserModelObject/rotateJoint:1.0
    //
    public boolean
    rotateJoint()
    {
        org.omg.CORBA.portable.Delegate _ob_delegate = _get_delegate();
        while(true)
        {
            synchronized(_ob_delegate)
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("_get_rotateJoint", true);
                    in = _invoke(out);
                    boolean _ob_r = in.read_boolean();
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
            }
        }
    }

    //
    // IDL:ParserModelObject/mass:1.0
    //
    public double
    mass()
    {
        org.omg.CORBA.portable.Delegate _ob_delegate = _get_delegate();
        while(true)
        {
            synchronized(_ob_delegate)
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("_get_mass", true);
                    in = _invoke(out);
                    double _ob_r = in.read_double();
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
            }
        }
    }

    //
    // IDL:ParserModelObject/jointValue:1.0
    //
    public double
    jointValue()
    {
        org.omg.CORBA.portable.Delegate _ob_delegate = _get_delegate();
        while(true)
        {
            synchronized(_ob_delegate)
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("_get_jointValue", true);
                    in = _invoke(out);
                    double _ob_r = in.read_double();
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
            }
        }
    }

    //
    // IDL:ParserModelObject/jointVel:1.0
    //
    public double
    jointVel()
    {
        org.omg.CORBA.portable.Delegate _ob_delegate = _get_delegate();
        while(true)
        {
            synchronized(_ob_delegate)
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("_get_jointVel", true);
                    in = _invoke(out);
                    double _ob_r = in.read_double();
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
            }
        }
    }

    //
    // IDL:ParserModelObject/jointAcc:1.0
    //
    public double
    jointAcc()
    {
        org.omg.CORBA.portable.Delegate _ob_delegate = _get_delegate();
        while(true)
        {
            synchronized(_ob_delegate)
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("_get_jointAcc", true);
                    in = _invoke(out);
                    double _ob_r = in.read_double();
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
            }
        }
    }

    //
    // IDL:ParserModelObject/absPos:1.0
    //
    public double[]
    absPos()
    {
        org.omg.CORBA.portable.Delegate _ob_delegate = _get_delegate();
        while(true)
        {
            synchronized(_ob_delegate)
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("_get_absPos", true);
                    in = _invoke(out);
                    double[] _ob_r = ValueMatrixHelper.read(in);
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
            }
        }
    }

    //
    // IDL:ParserModelObject/relPos:1.0
    //
    public double[]
    relPos()
    {
        org.omg.CORBA.portable.Delegate _ob_delegate = _get_delegate();
        while(true)
        {
            synchronized(_ob_delegate)
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("_get_relPos", true);
                    in = _invoke(out);
                    double[] _ob_r = ValueMatrixHelper.read(in);
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
            }
        }
    }

    //
    // IDL:ParserModelObject/relComPos:1.0
    //
    public double[]
    relComPos()
    {
        org.omg.CORBA.portable.Delegate _ob_delegate = _get_delegate();
        while(true)
        {
            synchronized(_ob_delegate)
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("_get_relComPos", true);
                    in = _invoke(out);
                    double[] _ob_r = ValueMatrixHelper.read(in);
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
            }
        }
    }

    //
    // IDL:ParserModelObject/absComPos:1.0
    //
    public double[]
    absComPos()
    {
        org.omg.CORBA.portable.Delegate _ob_delegate = _get_delegate();
        while(true)
        {
            synchronized(_ob_delegate)
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("_get_absComPos", true);
                    in = _invoke(out);
                    double[] _ob_r = ValueMatrixHelper.read(in);
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
            }
        }
    }

    //
    // IDL:ParserModelObject/relComAcc:1.0
    //
    public double[]
    relComAcc()
    {
        org.omg.CORBA.portable.Delegate _ob_delegate = _get_delegate();
        while(true)
        {
            synchronized(_ob_delegate)
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("_get_relComAcc", true);
                    in = _invoke(out);
                    double[] _ob_r = ValueMatrixHelper.read(in);
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
            }
        }
    }

    //
    // IDL:ParserModelObject/omega:1.0
    //
    public double[]
    omega()
    {
        org.omg.CORBA.portable.Delegate _ob_delegate = _get_delegate();
        while(true)
        {
            synchronized(_ob_delegate)
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("_get_omega", true);
                    in = _invoke(out);
                    double[] _ob_r = ValueMatrixHelper.read(in);
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
            }
        }
    }

    //
    // IDL:ParserModelObject/omega_d:1.0
    //
    public double[]
    omega_d()
    {
        org.omg.CORBA.portable.Delegate _ob_delegate = _get_delegate();
        while(true)
        {
            synchronized(_ob_delegate)
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("_get_omega_d", true);
                    in = _invoke(out);
                    double[] _ob_r = ValueMatrixHelper.read(in);
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
            }
        }
    }

    //
    // IDL:ParserModelObject/relAcc:1.0
    //
    public double[]
    relAcc()
    {
        org.omg.CORBA.portable.Delegate _ob_delegate = _get_delegate();
        while(true)
        {
            synchronized(_ob_delegate)
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("_get_relAcc", true);
                    in = _invoke(out);
                    double[] _ob_r = ValueMatrixHelper.read(in);
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
            }
        }
    }

    //
    // IDL:ParserModelObject/absVel:1.0
    //
    public double[]
    absVel()
    {
        org.omg.CORBA.portable.Delegate _ob_delegate = _get_delegate();
        while(true)
        {
            synchronized(_ob_delegate)
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("_get_absVel", true);
                    in = _invoke(out);
                    double[] _ob_r = ValueMatrixHelper.read(in);
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
            }
        }
    }

    //
    // IDL:ParserModelObject/absComVel:1.0
    //
    public double[]
    absComVel()
    {
        org.omg.CORBA.portable.Delegate _ob_delegate = _get_delegate();
        while(true)
        {
            synchronized(_ob_delegate)
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("_get_absComVel", true);
                    in = _invoke(out);
                    double[] _ob_r = ValueMatrixHelper.read(in);
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
            }
        }
    }

    //
    // IDL:ParserModelObject/relForce:1.0
    //
    public double[]
    relForce()
    {
        org.omg.CORBA.portable.Delegate _ob_delegate = _get_delegate();
        while(true)
        {
            synchronized(_ob_delegate)
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("_get_relForce", true);
                    in = _invoke(out);
                    double[] _ob_r = ValueMatrixHelper.read(in);
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
            }
        }
    }

    //
    // IDL:ParserModelObject/relTorque:1.0
    //
    public double[]
    relTorque()
    {
        org.omg.CORBA.portable.Delegate _ob_delegate = _get_delegate();
        while(true)
        {
            synchronized(_ob_delegate)
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("_get_relTorque", true);
                    in = _invoke(out);
                    double[] _ob_r = ValueMatrixHelper.read(in);
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
            }
        }
    }

    //
    // IDL:ParserModelObject/absAttitude:1.0
    //
    public double[]
    absAttitude()
    {
        org.omg.CORBA.portable.Delegate _ob_delegate = _get_delegate();
        while(true)
        {
            synchronized(_ob_delegate)
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("_get_absAttitude", true);
                    in = _invoke(out);
                    double[] _ob_r = ValueMatrixHelper.read(in);
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
            }
        }
    }

    //
    // IDL:ParserModelObject/relAttitude:1.0
    //
    public double[]
    relAttitude()
    {
        org.omg.CORBA.portable.Delegate _ob_delegate = _get_delegate();
        while(true)
        {
            synchronized(_ob_delegate)
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("_get_relAttitude", true);
                    in = _invoke(out);
                    double[] _ob_r = ValueMatrixHelper.read(in);
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
            }
        }
    }

    //
    // IDL:ParserModelObject/inertia:1.0
    //
    public double[]
    inertia()
    {
        org.omg.CORBA.portable.Delegate _ob_delegate = _get_delegate();
        while(true)
        {
            synchronized(_ob_delegate)
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("_get_inertia", true);
                    in = _invoke(out);
                    double[] _ob_r = ValueMatrixHelper.read(in);
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
            }
        }
    }

    //
    // IDL:ParserModelObject/dh:1.0
    //
    public double[]
    dh()
    {
        org.omg.CORBA.portable.Delegate _ob_delegate = _get_delegate();
        while(true)
        {
            synchronized(_ob_delegate)
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("_get_dh", true);
                    in = _invoke(out);
                    double[] _ob_r = ValueHelper.read(in);
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
            }
        }
    }

    //
    // IDL:ParserModelObject/ulimit:1.0
    //
    public double[]
    ulimit()
    {
        org.omg.CORBA.portable.Delegate _ob_delegate = _get_delegate();
        while(true)
        {
            synchronized(_ob_delegate)
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("_get_ulimit", true);
                    in = _invoke(out);
                    double[] _ob_r = ValueHelper.read(in);
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
            }
        }
    }

    //
    // IDL:ParserModelObject/llimit:1.0
    //
    public double[]
    llimit()
    {
        org.omg.CORBA.portable.Delegate _ob_delegate = _get_delegate();
        while(true)
        {
            synchronized(_ob_delegate)
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("_get_llimit", true);
                    in = _invoke(out);
                    double[] _ob_r = ValueHelper.read(in);
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
            }
        }
    }

    //
    // IDL:ParserModelObject/uvlimit:1.0
    //
    public double[]
    uvlimit()
    {
        org.omg.CORBA.portable.Delegate _ob_delegate = _get_delegate();
        while(true)
        {
            synchronized(_ob_delegate)
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("_get_uvlimit", true);
                    in = _invoke(out);
                    double[] _ob_r = ValueHelper.read(in);
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
            }
        }
    }

    //
    // IDL:ParserModelObject/lvlimit:1.0
    //
    public double[]
    lvlimit()
    {
        org.omg.CORBA.portable.Delegate _ob_delegate = _get_delegate();
        while(true)
        {
            synchronized(_ob_delegate)
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("_get_lvlimit", true);
                    in = _invoke(out);
                    double[] _ob_r = ValueHelper.read(in);
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
            }
        }
    }

    //
    // IDL:ParserModelObject/rotorInertia:1.0
    //
    public double
    rotorInertia()
    {
        org.omg.CORBA.portable.Delegate _ob_delegate = _get_delegate();
        while(true)
        {
            synchronized(_ob_delegate)
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("_get_rotorInertia", true);
                    in = _invoke(out);
                    double _ob_r = in.read_double();
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
            }
        }
    }

    //
    // IDL:ParserModelObject/rotorResistor:1.0
    //
    public double
    rotorResistor()
    {
        org.omg.CORBA.portable.Delegate _ob_delegate = _get_delegate();
        while(true)
        {
            synchronized(_ob_delegate)
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("_get_rotorResistor", true);
                    in = _invoke(out);
                    double _ob_r = in.read_double();
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
            }
        }
    }

    //
    // IDL:ParserModelObject/gearRatio:1.0
    //
    public double
    gearRatio()
    {
        org.omg.CORBA.portable.Delegate _ob_delegate = _get_delegate();
        while(true)
        {
            synchronized(_ob_delegate)
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("_get_gearRatio", true);
                    in = _invoke(out);
                    double _ob_r = in.read_double();
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
            }
        }
    }

    //
    // IDL:ParserModelObject/torqueConst:1.0
    //
    public double
    torqueConst()
    {
        org.omg.CORBA.portable.Delegate _ob_delegate = _get_delegate();
        while(true)
        {
            synchronized(_ob_delegate)
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("_get_torqueConst", true);
                    in = _invoke(out);
                    double _ob_r = in.read_double();
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
            }
        }
    }

    //
    // IDL:ParserModelObject/encoderPulse:1.0
    //
    public double
    encoderPulse()
    {
        org.omg.CORBA.portable.Delegate _ob_delegate = _get_delegate();
        while(true)
        {
            synchronized(_ob_delegate)
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("_get_encoderPulse", true);
                    in = _invoke(out);
                    double _ob_r = in.read_double();
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
            }
        }
    }

    //
    // IDL:ParserModelObject/bboxCenter:1.0
    //
    public double[]
    bboxCenter()
    {
        org.omg.CORBA.portable.Delegate _ob_delegate = _get_delegate();
        while(true)
        {
            synchronized(_ob_delegate)
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("_get_bboxCenter", true);
                    in = _invoke(out);
                    double[] _ob_r = ValueHelper.read(in);
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
            }
        }
    }

    //
    // IDL:ParserModelObject/bboxSize:1.0
    //
    public double[]
    bboxSize()
    {
        org.omg.CORBA.portable.Delegate _ob_delegate = _get_delegate();
        while(true)
        {
            synchronized(_ob_delegate)
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("_get_bboxSize", true);
                    in = _invoke(out);
                    double[] _ob_r = ValueHelper.read(in);
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
            }
        }
    }

    //
    // IDL:ParserModelObject/name:1.0
    //
    public String
    name()
    {
        org.omg.CORBA.portable.Delegate _ob_delegate = _get_delegate();
        while(true)
        {
            synchronized(_ob_delegate)
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("_get_name", true);
                    in = _invoke(out);
                    String _ob_r = in.read_string();
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
            }
        }
    }

    //
    // IDL:ParserModelObject/jointType:1.0
    //
    public String
    jointType()
    {
        org.omg.CORBA.portable.Delegate _ob_delegate = _get_delegate();
        while(true)
        {
            synchronized(_ob_delegate)
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("_get_jointType", true);
                    in = _invoke(out);
                    String _ob_r = in.read_string();
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
            }
        }
    }

    //
    // IDL:ParserModelObject/jointId:1.0
    //
    public short
    jointId()
    {
        org.omg.CORBA.portable.Delegate _ob_delegate = _get_delegate();
        while(true)
        {
            synchronized(_ob_delegate)
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("_get_jointId", true);
                    in = _invoke(out);
                    short _ob_r = in.read_short();
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
            }
        }
    }

    //
    // IDL:ParserModelObject/jointAxis:1.0
    //
    public String
    jointAxis()
    {
        org.omg.CORBA.portable.Delegate _ob_delegate = _get_delegate();
        while(true)
        {
            synchronized(_ob_delegate)
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("_get_jointAxis", true);
                    in = _invoke(out);
                    String _ob_r = in.read_string();
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
            }
        }
    }

    //
    // IDL:ParserModelObject/mother:1.0
    //
    public int
    mother()
    {
        org.omg.CORBA.portable.Delegate _ob_delegate = _get_delegate();
        while(true)
        {
            synchronized(_ob_delegate)
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("_get_mother", true);
                    in = _invoke(out);
                    int _ob_r = in.read_long();
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
            }
        }
    }

    //
    // IDL:ParserModelObject/sister:1.0
    //
    public int
    sister()
    {
        org.omg.CORBA.portable.Delegate _ob_delegate = _get_delegate();
        while(true)
        {
            synchronized(_ob_delegate)
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("_get_sister", true);
                    in = _invoke(out);
                    int _ob_r = in.read_long();
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
            }
        }
    }

    //
    // IDL:ParserModelObject/daughter:1.0
    //
    public int
    daughter()
    {
        org.omg.CORBA.portable.Delegate _ob_delegate = _get_delegate();
        while(true)
        {
            synchronized(_ob_delegate)
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("_get_daughter", true);
                    in = _invoke(out);
                    int _ob_r = in.read_long();
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
            }
        }
    }

    //
    // IDL:ParserModelObject/sensors:1.0
    //
    public SensorInfo[]
    sensors()
    {
        org.omg.CORBA.portable.Delegate _ob_delegate = _get_delegate();
        while(true)
        {
            synchronized(_ob_delegate)
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("_get_sensors", true);
                    in = _invoke(out);
                    SensorInfo[] _ob_r = SensorInfoSeqHelper.read(in);
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
            }
        }
    }
}
