// **********************************************************************
//
// Generated by the Orbix/E IDL to Java Translator
//
// Copyright (c) 2003
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 2.0.1

package jp.go.aist.jrl.vision;

//
// IDL:Camera:1.0
//
final public class CameraHolder implements org.omg.CORBA.portable.Streamable
{
    public Camera value;

    public
    CameraHolder()
    {
    }

    public
    CameraHolder(Camera initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = CameraHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        CameraHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return CameraHelper.type();
    }
}
