// **********************************************************************
//
// Generated by the Orbix/E IDL to Java Translator
//
// Copyright (c) 2003
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 2.0.1

package jp.go.aist.jrl.vision;

//
// IDL:Camera:1.0
//
public abstract class CameraPOA
    extends org.omg.PortableServer.Servant
    implements org.omg.CORBA.portable.InvokeHandler,
               CameraOperations
{
    static final String[] _ob_ids_ =
    {
        "IDL:Camera:1.0",
    };

    public Camera
    _this()
    {
        return CameraHelper.narrow(super._this_object());
    }

    public Camera
    _this(org.omg.CORBA.ORB orb)
    {
        return CameraHelper.narrow(super._this_object(orb));
    }

    public String[]
    _all_interfaces(org.omg.PortableServer.POA poa, byte[] objectId)
    {
        return _ob_ids_;
    }

    public org.omg.CORBA.portable.OutputStream
    _invoke(String opName,
            org.omg.CORBA.portable.InputStream in,
            org.omg.CORBA.portable.ResponseHandler handler)
    {
        final String[] _ob_names =
        {
            "destroy",
            "getCameraParameter",
            "getColorBuffer",
            "getDepthBuffer",
            "getImageData"
        };

        int _ob_left = 0;
        int _ob_right = _ob_names.length;
        int _ob_index = -1;

        while(_ob_left < _ob_right)
        {
            int _ob_m = (_ob_left + _ob_right) / 2;
            int _ob_res = _ob_names[_ob_m].compareTo(opName);
            if(_ob_res == 0)
            {
                _ob_index = _ob_m;
                break;
            }
            else if(_ob_res > 0)
                _ob_right = _ob_m;
            else
                _ob_left = _ob_m + 1;
        }

        switch(_ob_index)
        {
        case 0: // destroy
            return _OB_op_destroy(in, handler);

        case 1: // getCameraParameter
            return _OB_op_getCameraParameter(in, handler);

        case 2: // getColorBuffer
            return _OB_op_getColorBuffer(in, handler);

        case 3: // getDepthBuffer
            return _OB_op_getDepthBuffer(in, handler);

        case 4: // getImageData
            return _OB_op_getImageData(in, handler);
        }

        throw new org.omg.CORBA.BAD_OPERATION();
    }

    private org.omg.CORBA.portable.OutputStream
    _OB_op_destroy(org.omg.CORBA.portable.InputStream in,
                   org.omg.CORBA.portable.ResponseHandler handler)
    {
        org.omg.CORBA.portable.OutputStream out = null;
        destroy();
        out = handler.createReply();
        return out;
    }

    private org.omg.CORBA.portable.OutputStream
    _OB_op_getCameraParameter(org.omg.CORBA.portable.InputStream in,
                              org.omg.CORBA.portable.ResponseHandler handler)
    {
        org.omg.CORBA.portable.OutputStream out = null;
        jp.go.aist.jrl.vision.CameraPackage.CameraParameter _ob_r = getCameraParameter();
        out = handler.createReply();
        jp.go.aist.jrl.vision.CameraPackage.CameraParameterHelper.write(out, _ob_r);
        return out;
    }

    private org.omg.CORBA.portable.OutputStream
    _OB_op_getColorBuffer(org.omg.CORBA.portable.InputStream in,
                          org.omg.CORBA.portable.ResponseHandler handler)
    {
        org.omg.CORBA.portable.OutputStream out = null;
        int[] _ob_r = getColorBuffer();
        out = handler.createReply();
        ColorBufferHelper.write(out, _ob_r);
        return out;
    }

    private org.omg.CORBA.portable.OutputStream
    _OB_op_getDepthBuffer(org.omg.CORBA.portable.InputStream in,
                          org.omg.CORBA.portable.ResponseHandler handler)
    {
        org.omg.CORBA.portable.OutputStream out = null;
        float[] _ob_r = getDepthBuffer();
        out = handler.createReply();
        DepthBufferHelper.write(out, _ob_r);
        return out;
    }

    private org.omg.CORBA.portable.OutputStream
    _OB_op_getImageData(org.omg.CORBA.portable.InputStream in,
                        org.omg.CORBA.portable.ResponseHandler handler)
    {
        org.omg.CORBA.portable.OutputStream out = null;
        ImageData _ob_r = getImageData();
        out = handler.createReply();
        ImageDataHelper.write(out, _ob_r);
        return out;
    }
}
