// **********************************************************************
//
// Generated by the Orbix/E IDL to Java Translator
//
// Copyright (c) 2003
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 2.0.1

package jp.go.aist.jrl.vision;

//
// IDL:CBREP_Cnet:1.0
//
/***/

final public class CBREP_Cnet
{
    private static final String _ob_id = "IDL:CBREP_Cnet:1.0";

    public
    CBREP_Cnet()
    {
    }

    public
    CBREP_Cnet(int label,
               int n,
               int mapcol,
               int maprow,
               float[] Position,
               float[] Normal,
               byte red,
               byte green,
               byte blue)
    {
        this.label = label;
        this.n = n;
        this.mapcol = mapcol;
        this.maprow = maprow;
        this.Position = Position;
        this.Normal = Normal;
        this.red = red;
        this.green = green;
        this.blue = blue;
    }

    public int label;
    public int n;
    public int mapcol;
    public int maprow;
    public float[] Position;
    public float[] Normal;
    public byte red;
    public byte green;
    public byte blue;
}
