// **********************************************************************
//
// Generated by the Orbix/E IDL to Java Translator
//
// Copyright (c) 2003
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 2.0.1

package jp.go.aist.jrl.vision;

//
// IDL:CBREP_SegmentSeq:1.0
//
final public class CBREP_SegmentSeqHelper
{
    public static void
    insert(org.omg.CORBA.Any any, CBREP_Segment[] val)
    {
        org.omg.CORBA.portable.OutputStream out = any.create_output_stream();
        write(out, val);
        any.read_value(out.create_input_stream(), type());
    }

    public static CBREP_Segment[]
    extract(org.omg.CORBA.Any any)
    {
        if(any.type().equivalent(type()))
            return read(any.create_input_stream());
        else
            throw new org.omg.CORBA.BAD_OPERATION();
    }

    private static org.omg.CORBA.TypeCode typeCode_;

    public static org.omg.CORBA.TypeCode
    type()
    {
        if(typeCode_ == null)
        {
            org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init();
            typeCode_ = orb.create_alias_tc(id(), "CBREP_SegmentSeq", orb.create_sequence_tc(0, CBREP_SegmentHelper.type()));
        }

        return typeCode_;
    }

    public static String
    id()
    {
        return "IDL:CBREP_SegmentSeq:1.0";
    }

    public static CBREP_Segment[]
    read(org.omg.CORBA.portable.InputStream in)
    {
        CBREP_Segment[] _ob_v;
        int len0 = in.read_ulong();
        _ob_v = new CBREP_Segment[len0];
        for(int i0 = 0 ; i0 < len0 ; i0++)
            _ob_v[i0] = CBREP_SegmentHelper.read(in);
        return _ob_v;
    }

    public static void
    write(org.omg.CORBA.portable.OutputStream out, CBREP_Segment[] val)
    {
        int len0 = val.length;
        out.write_ulong(len0);
        for(int i0 = 0 ; i0 < len0 ; i0++)
            CBREP_SegmentHelper.write(out, val[i0]);
    }
}
