// **********************************************************************
//
// Generated by the Orbix/E IDL to Java Translator
//
// Copyright (c) 2003
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 2.0.1

package jp.go.aist.jrl.vision;

//
// IDL:CBREP_Point:1.0
//
/***/

final public class CBREP_Point
{
    private static final String _ob_id = "IDL:CBREP_Point:1.0";

    public
    CBREP_Point()
    {
    }

    public
    CBREP_Point(int label,
                int n,
                int row,
                int col,
                float rowd,
                float cold,
                float Xr,
                float Yr,
                float x,
                float y,
                float z,
                float normals,
                float[] Normal,
                float[] Tangent,
                float curvature,
                float error,
                byte red,
                byte green,
                byte blue)
    {
        this.label = label;
        this.n = n;
        this.row = row;
        this.col = col;
        this.rowd = rowd;
        this.cold = cold;
        this.Xr = Xr;
        this.Yr = Yr;
        this.x = x;
        this.y = y;
        this.z = z;
        this.normals = normals;
        this.Normal = Normal;
        this.Tangent = Tangent;
        this.curvature = curvature;
        this.error = error;
        this.red = red;
        this.green = green;
        this.blue = blue;
    }

    public int label;
    public int n;
    public int row;
    public int col;
    public float rowd;
    public float cold;
    public float Xr;
    public float Yr;
    public float x;
    public float y;
    public float z;
    public float normals;
    public float[] Normal;
    public float[] Tangent;
    public float curvature;
    public float error;
    public byte red;
    public byte green;
    public byte blue;
}
