// **********************************************************************
//
// Generated by the Orbix/E IDL to Java Translator
//
// Copyright (c) 2003
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 2.0.1

package jp.go.aist.jrl.vision;

//
// IDL:CBREP:1.0
//
final public class CBREPHelper
{
    public static void
    insert(org.omg.CORBA.Any any, CBREP val)
    {
        org.omg.CORBA.portable.OutputStream out = any.create_output_stream();
        write(out, val);
        any.read_value(out.create_input_stream(), type());
    }

    public static CBREP
    extract(org.omg.CORBA.Any any)
    {
        if(any.type().equivalent(type()))
            return read(any.create_input_stream());
        else
            throw new org.omg.CORBA.BAD_OPERATION();
    }

    private static org.omg.CORBA.TypeCode typeCode_;

    public static org.omg.CORBA.TypeCode
    type()
    {
        if(typeCode_ == null)
        {
            org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init();
            org.omg.CORBA.StructMember[] members = new org.omg.CORBA.StructMember[17];

            members[0] = new org.omg.CORBA.StructMember();
            members[0].name = "label";
            members[0].type = orb.get_primitive_tc(org.omg.CORBA.TCKind.tk_long);

            members[1] = new org.omg.CORBA.StructMember();
            members[1].name = "n";
            members[1].type = orb.get_primitive_tc(org.omg.CORBA.TCKind.tk_long);

            members[2] = new org.omg.CORBA.StructMember();
            members[2].name = "nregion";
            members[2].type = orb.get_primitive_tc(org.omg.CORBA.TCKind.tk_long);

            members[3] = new org.omg.CORBA.StructMember();
            members[3].name = "nbound";
            members[3].type = orb.get_primitive_tc(org.omg.CORBA.TCKind.tk_long);

            members[4] = new org.omg.CORBA.StructMember();
            members[4].name = "nsegment";
            members[4].type = orb.get_primitive_tc(org.omg.CORBA.TCKind.tk_long);

            members[5] = new org.omg.CORBA.StructMember();
            members[5].name = "npoint";
            members[5].type = orb.get_primitive_tc(org.omg.CORBA.TCKind.tk_long);

            members[6] = new org.omg.CORBA.StructMember();
            members[6].name = "ncnet";
            members[6].type = orb.get_primitive_tc(org.omg.CORBA.TCKind.tk_long);

            members[7] = new org.omg.CORBA.StructMember();
            members[7].name = "colstart";
            members[7].type = orb.get_primitive_tc(org.omg.CORBA.TCKind.tk_long);

            members[8] = new org.omg.CORBA.StructMember();
            members[8].name = "rowstart";
            members[8].type = orb.get_primitive_tc(org.omg.CORBA.TCKind.tk_long);

            members[9] = new org.omg.CORBA.StructMember();
            members[9].name = "ncol";
            members[9].type = orb.get_primitive_tc(org.omg.CORBA.TCKind.tk_long);

            members[10] = new org.omg.CORBA.StructMember();
            members[10].name = "nrow";
            members[10].type = orb.get_primitive_tc(org.omg.CORBA.TCKind.tk_long);

            members[11] = new org.omg.CORBA.StructMember();
            members[11].name = "region";
            members[11].type = CBREP_RegionSeqHelper.type();

            members[12] = new org.omg.CORBA.StructMember();
            members[12].name = "bound";
            members[12].type = CBREP_BoundSeqHelper.type();

            members[13] = new org.omg.CORBA.StructMember();
            members[13].name = "segment";
            members[13].type = CBREP_SegmentSeqHelper.type();

            members[14] = new org.omg.CORBA.StructMember();
            members[14].name = "point";
            members[14].type = CBREP_PointSeqHelper.type();

            members[15] = new org.omg.CORBA.StructMember();
            members[15].name = "cnet";
            members[15].type = CBREP_CnetSeqHelper.type();

            members[16] = new org.omg.CORBA.StructMember();
            members[16].name = "CameraID";
            members[16].type = orb.get_primitive_tc(org.omg.CORBA.TCKind.tk_long);

            typeCode_ = orb.create_struct_tc(id(), "CBREP", members);
        }

        return typeCode_;
    }

    public static String
    id()
    {
        return "IDL:CBREP:1.0";
    }

    public static CBREP
    read(org.omg.CORBA.portable.InputStream in)
    {
        CBREP _ob_v = new CBREP();
        _ob_v.label = in.read_long();
        _ob_v.n = in.read_long();
        _ob_v.nregion = in.read_long();
        _ob_v.nbound = in.read_long();
        _ob_v.nsegment = in.read_long();
        _ob_v.npoint = in.read_long();
        _ob_v.ncnet = in.read_long();
        _ob_v.colstart = in.read_long();
        _ob_v.rowstart = in.read_long();
        _ob_v.ncol = in.read_long();
        _ob_v.nrow = in.read_long();
        _ob_v.region = CBREP_RegionSeqHelper.read(in);
        _ob_v.bound = CBREP_BoundSeqHelper.read(in);
        _ob_v.segment = CBREP_SegmentSeqHelper.read(in);
        _ob_v.point = CBREP_PointSeqHelper.read(in);
        _ob_v.cnet = CBREP_CnetSeqHelper.read(in);
        _ob_v.CameraID = in.read_long();
        return _ob_v;
    }

    public static void
    write(org.omg.CORBA.portable.OutputStream out, CBREP val)
    {
        out.write_long(val.label);
        out.write_long(val.n);
        out.write_long(val.nregion);
        out.write_long(val.nbound);
        out.write_long(val.nsegment);
        out.write_long(val.npoint);
        out.write_long(val.ncnet);
        out.write_long(val.colstart);
        out.write_long(val.rowstart);
        out.write_long(val.ncol);
        out.write_long(val.nrow);
        CBREP_RegionSeqHelper.write(out, val.region);
        CBREP_BoundSeqHelper.write(out, val.bound);
        CBREP_SegmentSeqHelper.write(out, val.segment);
        CBREP_PointSeqHelper.write(out, val.point);
        CBREP_CnetSeqHelper.write(out, val.cnet);
        out.write_long(val.CameraID);
    }
}
