// **********************************************************************
//
// Generated by the Orbix/E IDL to Java Translator
//
// Copyright (c) 2003
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 2.0.1

package jp.go.aist.jrl.vision;

//
// IDL:CollisionData:1.0
//
final public class CollisionDataHolder implements org.omg.CORBA.portable.Streamable
{
    public CollisionData value;

    public
    CollisionDataHolder()
    {
    }

    public
    CollisionDataHolder(CollisionData initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = CollisionDataHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        CollisionDataHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return CollisionDataHelper.type();
    }
}
