// **********************************************************************
//
// Generated by the Orbix/E IDL to Java Translator
//
// Copyright (c) 2003
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 2.0.1

package jp.go.aist.jrl.vision;

//
// IDL:CollisionData:1.0
//
/**
 * コリジョン情報の詳細(接触点の座標、法線ベクトル)
 *
 * @member      coord   接触点の座標(ワールド座標系)
 * @member      normal  法線ベクトル(ワールド座標系)
 **/

final public class CollisionData
{
    private static final String _ob_id = "IDL:CollisionData:1.0";

    public
    CollisionData()
    {
    }

    public
    CollisionData(float[] coord,
                  float[] normal,
                  double idepth)
    {
        this.coord = coord;
        this.normal = normal;
        this.idepth = idepth;
    }

    public float[] coord;
    public float[] normal;
    public double idepth;
}
