// **********************************************************************
//
// Generated by the Orbix/E IDL to Java Translator
//
// Copyright (c) 2003
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 2.0.1

package jp.go.aist.jrl.vision;

//
// IDL:DataId:1.0
//
final public class DataIdHelper
{
    public static void
    insert(org.omg.CORBA.Any any, DataId val)
    {
        org.omg.CORBA.portable.OutputStream out = any.create_output_stream();
        write(out, val);
        any.read_value(out.create_input_stream(), type());
    }

    public static DataId
    extract(org.omg.CORBA.Any any)
    {
        if(any.type().equivalent(type()))
            return read(any.create_input_stream());
        else
            throw new org.omg.CORBA.BAD_OPERATION();
    }

    private static org.omg.CORBA.TypeCode typeCode_;

    public static org.omg.CORBA.TypeCode
    type()
    {
        if(typeCode_ == null)
        {
            org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init();
            String[] members = new String[3];
            members[0] = "ANGLE";
            members[1] = "VELOCITY";
            members[2] = "ACCELERATION";
            typeCode_ = orb.create_enum_tc(id(), "DataId", members);
        }

        return typeCode_;
    }

    public static String
    id()
    {
        return "IDL:DataId:1.0";
    }

    public static DataId
    read(org.omg.CORBA.portable.InputStream in)
    {
        DataId _ob_v;
        _ob_v = DataId.from_int(in.read_ulong());
        return _ob_v;
    }

    public static void
    write(org.omg.CORBA.portable.OutputStream out, DataId val)
    {
        out.write_ulong(val.value());
    }
}
