// **********************************************************************
//
// Generated by the Orbix/E IDL to Java Translator
//
// Copyright (c) 2003
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 2.0.1

package jp.go.aist.jrl.vision;

//
// IDL:HRP2Camera:1.0
//
/***/

public interface HRP2Camera extends HRP2CameraOperations,
                                    org.omg.CORBA.Object
{
}
