// **********************************************************************
//
// Generated by the Orbix/E IDL to Java Translator
//
// Copyright (c) 2003
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 2.0.1

package jp.go.aist.jrl.vision;

//
// IDL:ImageData:1.0
//
/***/

final public class ImageData
{
    private static final String _ob_id = "IDL:ImageData:1.0";

    public
    ImageData()
    {
    }

    public
    ImageData(PixelFormat format,
              int width,
              int height,
              byte[] octetData,
              int[] longData,
              float[] floatData)
    {
        this.format = format;
        this.width = width;
        this.height = height;
        this.octetData = octetData;
        this.longData = longData;
        this.floatData = floatData;
    }

    public PixelFormat format;
    public int width;
    public int height;
    public byte[] octetData;
    public int[] longData;
    public float[] floatData;
}
