// **********************************************************************
//
// Generated by the Orbix/E IDL to Java Translator
//
// Copyright (c) 2003
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 2.0.1

package jp.go.aist.jrl.vision;

//
// IDL:LinkDataSeq:1.0
//
final public class LinkDataSeqHolder implements org.omg.CORBA.portable.Streamable
{
    public double[][] value;

    public
    LinkDataSeqHolder()
    {
    }

    public
    LinkDataSeqHolder(double[][] initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = LinkDataSeqHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        LinkDataSeqHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return LinkDataSeqHelper.type();
    }
}
