// **********************************************************************
//
// Generated by the Orbix/E IDL to Java Translator
//
// Copyright (c) 2003
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 2.0.1

package jp.go.aist.jrl.vision;

//
// IDL:LinkValue:1.0
//
/**
 * リンク情報
 * @member      name    リンク名
 * @member      param   パラメタ名
 * @member      value   値
 **/

final public class LinkValue
{
    private static final String _ob_id = "IDL:LinkValue:1.0";

    public
    LinkValue()
    {
    }

    public
    LinkValue(String name,
              String param,
              double[] data)
    {
        this.name = name;
        this.param = param;
        this.data = data;
    }

    public String name;
    public String param;
    public double[] data;
}
