// **********************************************************************
//
// Generated by the Orbix/E IDL to Java Translator
//
// Copyright (c) 2003
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 2.0.1

package jp.go.aist.jrl.vision;

//
// IDL:ParserCharObject:1.0
//
final public class ParserCharObjectHolder implements org.omg.CORBA.portable.Streamable
{
    public ParserCharObject value;

    public
    ParserCharObjectHolder()
    {
    }

    public
    ParserCharObjectHolder(ParserCharObject initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = ParserCharObjectHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        ParserCharObjectHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return ParserCharObjectHelper.type();
    }
}
