// **********************************************************************
//
// Generated by the Orbix/E IDL to Java Translator
//
// Copyright (c) 2003
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 2.0.1

package jp.go.aist.jrl.vision;

//
// IDL:RobotState:1.0
//
/***/

final public class RobotState
{
    private static final String _ob_id = "IDL:RobotState:1.0";

    public
    RobotState()
    {
    }

    public
    RobotState(double[] angle,
               double[] velocity,
               double[][] force,
               double[][] rate,
               double[][] accel,
               double[][] attitude,
               double[] zmp,
               double[] waistPos,
               double[] waistRpy,
               ImageData[] image)
    {
        this.angle = angle;
        this.velocity = velocity;
        this.force = force;
        this.rate = rate;
        this.accel = accel;
        this.attitude = attitude;
        this.zmp = zmp;
        this.waistPos = waistPos;
        this.waistRpy = waistRpy;
        this.image = image;
    }

    public double[] angle;
    public double[] velocity;
    public double[][] force;
    public double[][] rate;
    public double[][] accel;
    public double[][] attitude;
    public double[] zmp;
    public double[] waistPos;
    public double[] waistRpy;
    public ImageData[] image;
}
