// **********************************************************************
//
// Generated by the Orbix/E IDL to Java Translator
//
// Copyright (c) 2003
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 2.0.1

package jp.go.aist.jrl.vision;

//
// IDL:SensorInfoSeq:1.0
//
final public class SensorInfoSeqHolder implements org.omg.CORBA.portable.Streamable
{
    public SensorInfo[] value;

    public
    SensorInfoSeqHolder()
    {
    }

    public
    SensorInfoSeqHolder(SensorInfo[] initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = SensorInfoSeqHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        SensorInfoSeqHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return SensorInfoSeqHelper.type();
    }
}
