// **********************************************************************
//
// Generated by the Orbix/E IDL to Java Translator
//
// Copyright (c) 2003
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 2.0.1

package jp.go.aist.jrl.vision;

//
// IDL:SensorInfo:1.0
//
public abstract class SensorInfoPOA
    extends org.omg.PortableServer.Servant
    implements org.omg.CORBA.portable.InvokeHandler,
               SensorInfoOperations
{
    static final String[] _ob_ids_ =
    {
        "IDL:SensorInfo:1.0",
    };

    public SensorInfo
    _this()
    {
        return SensorInfoHelper.narrow(super._this_object());
    }

    public SensorInfo
    _this(org.omg.CORBA.ORB orb)
    {
        return SensorInfoHelper.narrow(super._this_object(orb));
    }

    public String[]
    _all_interfaces(org.omg.PortableServer.POA poa, byte[] objectId)
    {
        return _ob_ids_;
    }

    public org.omg.CORBA.portable.OutputStream
    _invoke(String opName,
            org.omg.CORBA.portable.InputStream in,
            org.omg.CORBA.portable.ResponseHandler handler)
    {
        final String[] _ob_names =
        {
            "_get_id",
            "_get_maxValue",
            "_get_name",
            "_get_relAttitude",
            "_get_relPos",
            "_get_type"
        };

        int _ob_left = 0;
        int _ob_right = _ob_names.length;
        int _ob_index = -1;

        while(_ob_left < _ob_right)
        {
            int _ob_m = (_ob_left + _ob_right) / 2;
            int _ob_res = _ob_names[_ob_m].compareTo(opName);
            if(_ob_res == 0)
            {
                _ob_index = _ob_m;
                break;
            }
            else if(_ob_res > 0)
                _ob_right = _ob_m;
            else
                _ob_left = _ob_m + 1;
        }

        switch(_ob_index)
        {
        case 0: // _get_id
            return _OB_att_get_id(in, handler);

        case 1: // _get_maxValue
            return _OB_att_get_maxValue(in, handler);

        case 2: // _get_name
            return _OB_att_get_name(in, handler);

        case 3: // _get_relAttitude
            return _OB_att_get_relAttitude(in, handler);

        case 4: // _get_relPos
            return _OB_att_get_relPos(in, handler);

        case 5: // _get_type
            return _OB_att_get_type(in, handler);
        }

        throw new org.omg.CORBA.BAD_OPERATION();
    }

    private org.omg.CORBA.portable.OutputStream
    _OB_att_get_id(org.omg.CORBA.portable.InputStream in,
                   org.omg.CORBA.portable.ResponseHandler handler)
    {
        int _ob_r = id();
        org.omg.CORBA.portable.OutputStream out = handler.createReply();
        out.write_long(_ob_r);
        return out;
    }

    private org.omg.CORBA.portable.OutputStream
    _OB_att_get_maxValue(org.omg.CORBA.portable.InputStream in,
                         org.omg.CORBA.portable.ResponseHandler handler)
    {
        double[] _ob_r = maxValue();
        org.omg.CORBA.portable.OutputStream out = handler.createReply();
        ValueMatrixHelper.write(out, _ob_r);
        return out;
    }

    private org.omg.CORBA.portable.OutputStream
    _OB_att_get_name(org.omg.CORBA.portable.InputStream in,
                     org.omg.CORBA.portable.ResponseHandler handler)
    {
        String _ob_r = name();
        org.omg.CORBA.portable.OutputStream out = handler.createReply();
        out.write_string(_ob_r);
        return out;
    }

    private org.omg.CORBA.portable.OutputStream
    _OB_att_get_relAttitude(org.omg.CORBA.portable.InputStream in,
                            org.omg.CORBA.portable.ResponseHandler handler)
    {
        double[] _ob_r = relAttitude();
        org.omg.CORBA.portable.OutputStream out = handler.createReply();
        ValueMatrixHelper.write(out, _ob_r);
        return out;
    }

    private org.omg.CORBA.portable.OutputStream
    _OB_att_get_relPos(org.omg.CORBA.portable.InputStream in,
                       org.omg.CORBA.portable.ResponseHandler handler)
    {
        double[] _ob_r = relPos();
        org.omg.CORBA.portable.OutputStream out = handler.createReply();
        ValueMatrixHelper.write(out, _ob_r);
        return out;
    }

    private org.omg.CORBA.portable.OutputStream
    _OB_att_get_type(org.omg.CORBA.portable.InputStream in,
                     org.omg.CORBA.portable.ResponseHandler handler)
    {
        SensorType _ob_r = type();
        org.omg.CORBA.portable.OutputStream out = handler.createReply();
        SensorTypeHelper.write(out, _ob_r);
        return out;
    }
}
