// **********************************************************************
//
// Generated by the Orbix/E IDL to Java Translator
//
// Copyright (c) 2003
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 2.0.1

package jp.go.aist.jrl.vision;

//
// IDL:Transform:1.0
//
final public class TransformHelper
{
    public static void
    insert(org.omg.CORBA.Any any, Transform val)
    {
        org.omg.CORBA.portable.OutputStream out = any.create_output_stream();
        write(out, val);
        any.read_value(out.create_input_stream(), type());
    }

    public static Transform
    extract(org.omg.CORBA.Any any)
    {
        if(any.type().equivalent(type()))
            return read(any.create_input_stream());
        else
            throw new org.omg.CORBA.BAD_OPERATION();
    }

    private static org.omg.CORBA.TypeCode typeCode_;

    public static org.omg.CORBA.TypeCode
    type()
    {
        if(typeCode_ == null)
        {
            org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init();
            org.omg.CORBA.StructMember[] members = new org.omg.CORBA.StructMember[7];

            members[0] = new org.omg.CORBA.StructMember();
            members[0].name = "posX";
            members[0].type = orb.get_primitive_tc(org.omg.CORBA.TCKind.tk_float);

            members[1] = new org.omg.CORBA.StructMember();
            members[1].name = "posY";
            members[1].type = orb.get_primitive_tc(org.omg.CORBA.TCKind.tk_float);

            members[2] = new org.omg.CORBA.StructMember();
            members[2].name = "posZ";
            members[2].type = orb.get_primitive_tc(org.omg.CORBA.TCKind.tk_float);

            members[3] = new org.omg.CORBA.StructMember();
            members[3].name = "axisX";
            members[3].type = orb.get_primitive_tc(org.omg.CORBA.TCKind.tk_float);

            members[4] = new org.omg.CORBA.StructMember();
            members[4].name = "axisY";
            members[4].type = orb.get_primitive_tc(org.omg.CORBA.TCKind.tk_float);

            members[5] = new org.omg.CORBA.StructMember();
            members[5].name = "axisZ";
            members[5].type = orb.get_primitive_tc(org.omg.CORBA.TCKind.tk_float);

            members[6] = new org.omg.CORBA.StructMember();
            members[6].name = "angle";
            members[6].type = orb.get_primitive_tc(org.omg.CORBA.TCKind.tk_float);

            typeCode_ = orb.create_struct_tc(id(), "Transform", members);
        }

        return typeCode_;
    }

    public static String
    id()
    {
        return "IDL:Transform:1.0";
    }

    public static Transform
    read(org.omg.CORBA.portable.InputStream in)
    {
        Transform _ob_v = new Transform();
        _ob_v.posX = in.read_float();
        _ob_v.posY = in.read_float();
        _ob_v.posZ = in.read_float();
        _ob_v.axisX = in.read_float();
        _ob_v.axisY = in.read_float();
        _ob_v.axisZ = in.read_float();
        _ob_v.angle = in.read_float();
        return _ob_v;
    }

    public static void
    write(org.omg.CORBA.portable.OutputStream out, Transform val)
    {
        out.write_float(val.posX);
        out.write_float(val.posY);
        out.write_float(val.posZ);
        out.write_float(val.axisX);
        out.write_float(val.axisY);
        out.write_float(val.axisZ);
        out.write_float(val.angle);
    }
}
