// **********************************************************************
//
// Generated by the Orbix/E IDL to Java Translator
//
// Copyright (c) 2003
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 2.0.1

package jp.go.aist.jrl.vision;

//
// IDL:TransformQuaternion:1.0
//
final public class TransformQuaternionHelper
{
    public static void
    insert(org.omg.CORBA.Any any, TransformQuaternion val)
    {
        org.omg.CORBA.portable.OutputStream out = any.create_output_stream();
        write(out, val);
        any.read_value(out.create_input_stream(), type());
    }

    public static TransformQuaternion
    extract(org.omg.CORBA.Any any)
    {
        if(any.type().equivalent(type()))
            return read(any.create_input_stream());
        else
            throw new org.omg.CORBA.BAD_OPERATION();
    }

    private static org.omg.CORBA.TypeCode typeCode_;

    public static org.omg.CORBA.TypeCode
    type()
    {
        if(typeCode_ == null)
        {
            org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init();
            org.omg.CORBA.StructMember[] members = new org.omg.CORBA.StructMember[7];

            members[0] = new org.omg.CORBA.StructMember();
            members[0].name = "px";
            members[0].type = orb.get_primitive_tc(org.omg.CORBA.TCKind.tk_float);

            members[1] = new org.omg.CORBA.StructMember();
            members[1].name = "py";
            members[1].type = orb.get_primitive_tc(org.omg.CORBA.TCKind.tk_float);

            members[2] = new org.omg.CORBA.StructMember();
            members[2].name = "pz";
            members[2].type = orb.get_primitive_tc(org.omg.CORBA.TCKind.tk_float);

            members[3] = new org.omg.CORBA.StructMember();
            members[3].name = "qx";
            members[3].type = orb.get_primitive_tc(org.omg.CORBA.TCKind.tk_float);

            members[4] = new org.omg.CORBA.StructMember();
            members[4].name = "qy";
            members[4].type = orb.get_primitive_tc(org.omg.CORBA.TCKind.tk_float);

            members[5] = new org.omg.CORBA.StructMember();
            members[5].name = "qz";
            members[5].type = orb.get_primitive_tc(org.omg.CORBA.TCKind.tk_float);

            members[6] = new org.omg.CORBA.StructMember();
            members[6].name = "qw";
            members[6].type = orb.get_primitive_tc(org.omg.CORBA.TCKind.tk_float);

            typeCode_ = orb.create_struct_tc(id(), "TransformQuaternion", members);
        }

        return typeCode_;
    }

    public static String
    id()
    {
        return "IDL:TransformQuaternion:1.0";
    }

    public static TransformQuaternion
    read(org.omg.CORBA.portable.InputStream in)
    {
        TransformQuaternion _ob_v = new TransformQuaternion();
        _ob_v.px = in.read_float();
        _ob_v.py = in.read_float();
        _ob_v.pz = in.read_float();
        _ob_v.qx = in.read_float();
        _ob_v.qy = in.read_float();
        _ob_v.qz = in.read_float();
        _ob_v.qw = in.read_float();
        return _ob_v;
    }

    public static void
    write(org.omg.CORBA.portable.OutputStream out, TransformQuaternion val)
    {
        out.write_float(val.px);
        out.write_float(val.py);
        out.write_float(val.pz);
        out.write_float(val.qx);
        out.write_float(val.qy);
        out.write_float(val.qz);
        out.write_float(val.qw);
    }
}
