// **********************************************************************
//
// Generated by the Orbix/E IDL to Java Translator
//
// Copyright (c) 2003
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 2.0.1

package jp.go.aist.jrl.vision;

//
// IDL:Value:1.0
//
final public class ValueHolder implements org.omg.CORBA.portable.Streamable
{
    public double[] value;

    public
    ValueHolder()
    {
    }

    public
    ValueHolder(double[] initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = ValueHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        ValueHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return ValueHelper.type();
    }
}
