#include "common.idl"


interface ModelTrackerInterface{

  /* Object position in the camera frame*/
  struct HomogeneousMatrix
  {
    double cMo[4][4]; 
  };

  /*! Set estimation of the object position. */
  boolean SetcMo(in HomogeneousMatrix acMo);

  boolean SetcdMo(in HomogeneousMatrix aHM);

  /* Position of the object */
  boolean GetcMo(out HomogeneousMatrix acMo);

  /*! Debug information for the object. */
  struct DebugInfoObject
  {
    /*! Information of the image. */
    ImageData anImgData;

    /*! Homogeneous matrix. */
    HomogeneousMatrix aData;

  };

  /* Position of the object */
  boolean GetDebugInfoObject(out DebugInfoObject aDIO);


};
