// **********************************************************************
//
// Generated by the Orbix/E IDL to Java Translator
//
// Copyright (c) 2003
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 2.0.1

package jp.go.aist.jrl.vision.LowLevelVisionSystemPackage;

//
// IDL:LowLevelVisionSystem/InputMode:1.0
//
/***/

public class InputMode
{
    private static InputMode [] values_ = new InputMode[4];
    private int value_;

    public final static int _FRAMEGRABBER = 0;
    public final static InputMode FRAMEGRABBER = new InputMode(_FRAMEGRABBER);
    public final static int _FILES = 1;
    public final static InputMode FILES = new InputMode(_FILES);
    public final static int _FILESINGLE = 2;
    public final static InputMode FILESINGLE = new InputMode(_FILESINGLE);
    public final static int _SIMULATION = 3;
    public final static InputMode SIMULATION = new InputMode(_SIMULATION);

    protected
    InputMode(int value)
    {
        values_[value] = this;
        value_ = value;
    }

    public int
    value()
    {
        return value_;
    }

    public static InputMode
    from_int(int value)
    {
        if(value < values_.length)
            return values_[value];
        else
            throw new org.omg.CORBA.BAD_PARAM("Value (" + value  + ") out of range", 25, org.omg.CORBA.CompletionStatus.COMPLETED_NO);
    }
}
