// **********************************************************************
//
// Generated by the Orbix/E IDL to Java Translator
//
// Copyright (c) 2003
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 2.0.1

package jp.go.aist.jrl.vision.LowLevelVisionSystemPackage;

//
// IDL:LowLevelVisionSystem/VisionSensorException:1.0
//
/** Vision Sensor exception
 * @member description description of the exception
 **/

final public class VisionSensorException extends org.omg.CORBA.UserException
{
    private static final String _ob_id = "IDL:LowLevelVisionSystem/VisionSensorException:1.0";

    public
    VisionSensorException()
    {
        super(_ob_id);
    }

    public
    VisionSensorException(String description)
    {
        super(_ob_id);
        this.description = description;
    }

    public
    VisionSensorException(String _reason,
                          String description)
    {
        super(_ob_id + " " + _reason);
        this.description = description;
    }

    public String description;
}
