// **********************************************************************
//
// Generated by the Orbix/E IDL to Java Translator
//
// Copyright (c) 2003
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 2.0.1

package jp.go.aist.jrl.vision.HRP2CameraPackage;

//
// IDL:HRP2Camera/IntrinsicParameters:1.0
//
final public class IntrinsicParametersHelper
{
    public static void
    insert(org.omg.CORBA.Any any, IntrinsicParameters val)
    {
        org.omg.CORBA.portable.OutputStream out = any.create_output_stream();
        write(out, val);
        any.read_value(out.create_input_stream(), type());
    }

    public static IntrinsicParameters
    extract(org.omg.CORBA.Any any)
    {
        if(any.type().equivalent(type()))
            return read(any.create_input_stream());
        else
            throw new org.omg.CORBA.BAD_OPERATION();
    }

    private static org.omg.CORBA.TypeCode typeCode_;

    public static org.omg.CORBA.TypeCode
    type()
    {
        if(typeCode_ == null)
        {
            org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init();
            org.omg.CORBA.StructMember[] members = new org.omg.CORBA.StructMember[4];

            members[0] = new org.omg.CORBA.StructMember();
            members[0].name = "Focal";
            members[0].type = orb.get_primitive_tc(org.omg.CORBA.TCKind.tk_float);

            members[1] = new org.omg.CORBA.StructMember();
            members[1].name = "Scale";
            members[1].type = orb.create_array_tc(2, orb.get_primitive_tc(org.omg.CORBA.TCKind.tk_float));

            members[2] = new org.omg.CORBA.StructMember();
            members[2].name = "SkewFactor";
            members[2].type = orb.get_primitive_tc(org.omg.CORBA.TCKind.tk_float);

            members[3] = new org.omg.CORBA.StructMember();
            members[3].name = "ImageCenter";
            members[3].type = orb.create_array_tc(2, orb.get_primitive_tc(org.omg.CORBA.TCKind.tk_float));

            typeCode_ = orb.create_struct_tc(id(), "IntrinsicParameters", members);
        }

        return typeCode_;
    }

    public static String
    id()
    {
        return "IDL:HRP2Camera/IntrinsicParameters:1.0";
    }

    public static IntrinsicParameters
    read(org.omg.CORBA.portable.InputStream in)
    {
        IntrinsicParameters _ob_v = new IntrinsicParameters();
        _ob_v.Focal = in.read_float();
        int len0 = 2;
        _ob_v.Scale = new float[len0];
        in.read_float_array(_ob_v.Scale, 0, len0);
        _ob_v.SkewFactor = in.read_float();
        int len1 = 2;
        _ob_v.ImageCenter = new float[len1];
        in.read_float_array(_ob_v.ImageCenter, 0, len1);
        return _ob_v;
    }

    public static void
    write(org.omg.CORBA.portable.OutputStream out, IntrinsicParameters val)
    {
        out.write_float(val.Focal);
        int len0 = val.Scale.length;
        if(len0 != 2)
             throw new org.omg.CORBA.MARSHAL();
        out.write_float_array(val.Scale, 0, len0);
        out.write_float(val.SkewFactor);
        int len1 = val.ImageCenter.length;
        if(len1 != 2)
             throw new org.omg.CORBA.MARSHAL();
        out.write_float_array(val.ImageCenter, 0, len1);
    }
}
