// **********************************************************************
//
// Generated by the Orbix/E IDL to Java Translator
//
// Copyright (c) 2003
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 2.0.1

package jp.go.aist.jrl.vision.HRP2CameraPackage;

//
// IDL:HRP2Camera/ProjectiveParameters:1.0
//
final public class ProjectiveParametersHolder implements org.omg.CORBA.portable.Streamable
{
    public ProjectiveParameters value;

    public
    ProjectiveParametersHolder()
    {
    }

    public
    ProjectiveParametersHolder(ProjectiveParameters initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = ProjectiveParametersHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        ProjectiveParametersHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return ProjectiveParametersHelper.type();
    }
}
